djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("intro.urls")),
    path("", include("home.urls")),
    path("", include("student.urls")),
    path("", include('trainer.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name='login'),

    path("", include('django.contrib.auth.urls')),
    path("", include('userextend.urls')),
    path("", include('feedback.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#   aceasta linie de cod face parte din configurarea fisierelor statice
#   si este utilizata pentru a asigura afisarea corecta a fisiserului din media

# functia static() primeste 2 args:
# settings.MEDIA_URL reprezinta url de baza pentru fisierele media
# settings.MEDIA_ROOT reprezinta folderul fizic in care fisierele media sunt stocate

# In concluzie, serverul va putea prelua fisierele media prin intermediul url specificat

home/urls.py
from django.urls import path
from home import views

urlpatterns =[
    path('', views.HomeTemplateView.as_view(), name='home-page'),
]

feedback/models.py
from django.db import models

from trainer.models import Trainer


# Create your models here.


class Feedback(models.Model):

    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)
    message = models.TextField(max_length=400)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

student/models.py
from django.contrib.auth.models import User
from django.db import models

from trainer.models import Trainer


# Create your models here.


class Student(models.Model):

    gender_options = (
        ("male","MALE"),
        ("female","FEMALE")
    )

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    email = models.EmailField(max_length=100)
    description = models.TextField(max_length=500)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=6, choices=gender_options)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)
    profile = models.ImageField(upload_to='profiles_student/', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    #auto_now_add = stocheaza data si ora cand a fost adaugata inregistrarea. nu se mai modifica
    #auto_now = stocheaza data si ora cand a fost adaugata inregistrarea. se modifica dara atunci cand se fac modificari pe inregistrare.

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class HistoryStudent(models.Model):
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.message

trainer/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Trainer(models.Model):

    department_options = (('backend', 'Backend'),
                          ('frontend', 'Frontend'),
                          ('network', 'Network'))

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    course = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    department = models.CharField(max_length=10, choices=department_options)
    active = models.BooleanField(default=True)
    profile = models.ImageField(upload_to='profiles/', blank=True, null=True) #se poate pune si default = 'default.jpg', dar nu e neaparat nevoie. cred ca incarca baza de date aiurea...

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class HistoryTrainer(models.Model):
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.message

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}"
</head>
<body>
{% include 'navbar.html' %}
{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        .edit_a{
            background-color: red;
            color:white;!important
            text-align: center;
            text-decoration: none;
            padding: 14px 25px;
        }
    </style>
</head>
<body>
<div>
    <h2>Hello, {{ fullname }}</h2>
    <h4> Congratulations! Your account has been created!</h4>

    <br><br>

    <h4>Your username account is: {{ username }}</h4>

    <a href="http://127.0.0.1:8000" class="edit_a">Go to app</a>
</div>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home-page' %}">Django Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home-page' %}">Home</a>
                </li>

                {% if user.is_authenticated %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Intro
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'list-of-cars' %}">List of Cars</a></li>
                            <li><a class="dropdown-item" href="{% url 'list-of-cooking-books' %}">List of Cooking Books</a>
                            </li>
                        </ul>
                    </li>

                    {% if perms.student.add_student or perms.student.view_list_of_students %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Student
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.student.add_student %}
                                <li><a class="dropdown-item" href="{% url 'create-student' %}">Create a new Student</a></li>
                            {% endif %}
                            {% if perms.student.view_list_of_students %}
                                <li><a class="dropdown-item" href="{% url 'list-of-students' %}">List of Students</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}

                    {% if perms.trainer.add_trainer or perms.trainer.view_list_of_trainers %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Trainer
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.trainer.add_trainer %}
                                <li><a class="dropdown-item" href="{% url 'create-trainer' %}">Create a new Trainer</a></li>
                            {% endif %}
                            {% if perms.trainer.view_list_of_trainers %}
                                <li><a class="dropdown-item" href="{% url 'list-of-trainers' %}">List of Trainers</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}

                    {% if perms.trainer.view_list_of_trainers %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            All trainers
                        </a>
                        <ul class="dropdown-menu">
                            {% for trainer in trainers %}
                                <li><a class ="dropdown-item" href="{% url 'detailed-trainer' trainer.id %}">{{ trainer }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endif %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="False">Feedback</a>
                        <ul class="dropdown-menu">
                            {% if perms.feedback.add_feedback %}
                                <li><a class="dropdown-item" href="{% url 'create-feedback' %}">Create new feedback</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{%  url 'list-of-feedbacks' %}">List of feedbacks</a></li>
                        </ul>
                    </li>

                {% endif %}

            </ul>

            {% if user.is_authenticated %}

                <a href="{% url 'logout' %}" class="btn btn-outline-secondary"> Logout, {{ user.username }}</a>
                <form class="d-flex" method="get" action="{% url 'search' %}" role="search">
                    <input class="form-control me-2" name="filter" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-primary">Login</a>
                    <a href="{% url 'create-user' %}" class="btn btn-outline-secondary">Sign up</a>
                </div>

            {% endif %}

        </div>
    </div>
</nav>